# HYPERION - Docker Orchestrator
# Titan Protocol System 12/300
version: '3.8'

networks:
  titan_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

volumes:
  pg_data:
    name: titan_pg_data
  redis_data:
    name: titan_redis_data
